name: API

services:
  db:
    image: mysql:8.3.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workbench
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  api:
    depends_on:
      - db
    image: evanhighvolt/mon_api_img
    ports:
      - "9000:80"
    restart: always

    working_dir: /var/lib/api

