#name: API image
#
#on:
#  push:
#jobs:
#  docker-build-image-api:
#    runs-on: ubuntu-latest
#    needs:
#      build
#    steps:
#      - uses: action/checkout@v4
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Connect to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USER }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Download a single artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: package.jar
#          path: .
#      - name: List files in the repository
#        run: ls ${{ github.workspace }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USER }}/mon_api_img
#
#      - run: echo "This job is done "